language: python
python:
    - "2.7"
install:
    - sudo pip install pep8 coverage python-coveralls PyYAML
script:
# Test
    - coverage run --source=hybridbayes.py,matchers.py test.py
after_success:
# Upload test results
    - coveralls
