language: python
python:
    - "2.7"
install:
    - sudo pip install pep8 coverage python-coveralls PyYAML
script:
# Lint
    - pep8 *.py
# Test
    - coverage run test.py
after_success:
# Upload test results
    - coveralls

